spring:
  application:
    name: customer-service
  data:
    mongodb:
      authentication-database: admin
      username: mongo
      password: 123
      port: 27017
      database: customer
      host: localhost

server:
  port: 8090
