spring:
  application:
    name: customer-service
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: pass
      port: 27017
      database: customer
      host: localhost

server:
  port: 8090
