spring:
  application:
    name: order-service
    config:
      customer-url: http://localhost:8222/api/v1/customers
      payment-url: http://localhost:8222/api/v1/payments
      product-url: http://localhost:8222/api/v1/products

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/order
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.kshrd.orderservice.kafka.OrderConfirmation
server:
  port: 8070
